# Generated by Django 6.0 on 2026-04-09 11:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitComplaintTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('tenant_id', models.CharField(max_length=100)),
                ('workflow', models.CharField(choices=[('system', 'System'), ('healthservice', 'Healthservice')], max_length=50)),
                ('service_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'verbose_name': 'Digit Complaint Type',
                'db_table': 'digit_complaint_types',
                'indexes': [models.Index(fields=['facility', 'workflow', 'status'], name='digit_compl_facilit_855192_idx')],
                'constraints': [models.UniqueConstraint(fields=('facility', 'tenant_id', 'workflow'), name='unique_facility_tenant_workflow')],
            },
        ),
    ]
