# Generated by Django 6.0 on 2026-04-10 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_digit_integration', '0001_initial'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGRComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('app_context', models.JSONField(blank=True, default=dict)),
                ('service_code', models.CharField(max_length=100)),
                ('workflow', models.CharField(choices=[('system', 'System'), ('healthservice', 'Healthservice')], max_length=50)),
                ('pgr_ticket_id', models.CharField(max_length=100, null=True, unique=True)),
                ('pgr_status', models.CharField(choices=[('pending_sync', 'Pending Sync'), ('synced', 'Synced'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('sync_failed', 'Sync Failed')], max_length=50, null=True)),
                ('pgr_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('pgr_response', models.JSONField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PGR Complaints',
                'db_table': 'pgr_complaints',
                'indexes': [models.Index(fields=['facility', 'pgr_status'], name='pgr_complai_facilit_e9a5d4_idx'), models.Index(fields=['facility', 'pgr_status', 'pgr_last_synced_at'], name='pgr_complai_facilit_eb9728_idx')],
            },
        ),
    ]
